name: Publish pipeline

permissions:
  contents: read

on:
  workflow_dispatch:

  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  publish-artifacts:
    runs-on: ubuntu-22.04

    env:
      ENV: 'ci'
      NEXUS_USER: ${{ secrets.NEXUS_USER }}
      NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Import GPG Key
        uses: crazy-max/ghaction-import-gpg@v6
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
      - name: Publish artifacts
        run: |
          sbt -java-home "$JAVA_HOME_17_X64" clean +publishSigned sonatypeBundleRelease
